# Generated by Django 4.1.2 on 2023-12-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Menu name')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Visible item label')),
                ('href', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Link to referred page (in priority)')),
                ('named_url', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Link name to page')),
                ('menu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.menu', verbose_name='Related menu')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.menuitem', verbose_name='Linked parent')),
            ],
            options={
                'ordering': ['menu', 'id'],
            },
        ),
    ]
